server.port=8001
huggingface.api.token = ENC(RVfnV27gaD3FJoo9oShN4aM9wGk9TrAid6sIh+dYpDCT3I0elaD3QvHgsOdC7r2i9+SB4Ig7qVrhIE5T/xfUK9dozRWVhHvWQsmQWbNkD0A=)
gemini.api.key=ENC(oE5fgmBIVSn6gu7pnT6qjUzS4z8fY+eRhFqgb4VLgfPpkE/UVbALScDa3Fj034Sd5g7JD+jd9vqzLW9GnOpawtf0cH9YS0Dv4+a9E0GWj5I=)
gemini.ats.prompt=Act as an ATS resume analyzer. Analyze the following resume against the given job description and return a structured JSON response with the following fields:\n\
1. overallScore (0-100) - overall resume fit score\n\
2. foundKeywords - list of matched keywords from the job description\n\
3. missingKeywords - list of important missing keywords\n\
4. sections - each section has:\n\
   - name (e.g. Experience, Skills, Education, Formatting)\n\
   - score (0-100)\n\
   - recommendations (list of suggestions)\n\
\n\
RESUME:\n\
{{RESUME_CONTENT}}\n\
\n\
JOB DESCRIPTION:\n\
{{JOB_DESCRIPTION}}\n\
\n\
Respond ONLY with the JSON structure.

jasypt.encryptor.password=Aeiou@123
spring.application.name=ats-checker-springboot
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ENC(4St/t3rhrVryGbf2BzRif2doe2MCyLk9yhiROJQZlMRY1HXwOAVmHge97+8LcKQnq/a70zGXHZL5Jni/MUZUBg==)
spring.mail.password=ENC(ib43uBIx+Z+iUr0NzwwBlWt/1Sbx0vLCLYzTm6BYKK/gjlv7q0+NAlGVJ0bFKpQO3ksqfisLa7WI8WocJCYqKw==)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
